lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add-friend/$', add_friend, name='add-friend'),
    url(r'^validate-npm/$', validate_npm, name='validate-npm'),
    url(r'^delete-friend/(?P<npm>[0-9]+)/$', delete_friend, name='delete-friend'),
    url(r'^get-friend-list/$', friend_list_json, name='get-friend-list'),
    url(r'^daftar-teman/$', friend_list, name='friend-list')
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
from lab_2.views import index as index_baru

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^$', index_baru, name='index'),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
    url(r'^lab-3/', include(lab_3,namespace='lab-3')),
    url(r'^lab-4/', include(lab_4,namespace='lab-4')),
    url(r'^lab-5/', include(lab_5,namespace='lab-5')),
    url(r'^lab-6/', include(lab_6,namespace='lab-6')),
    url(r'^lab-7/', include(lab_7,namespace='lab-7')),
    url(r'^lab-8/', include(lab_8,namespace='lab-8')),
    url(r'^lab-9/', include(lab_9,namespace='lab-9')),
]

lab_7/models.py
from __future__ import unicode_literals
from django.db import models

# Create your models here.
class Friend(models.Model):
    friend_name = models.CharField(max_length=400)
    npm = models.CharField(max_length=250, unique=True)
    added_at = models.DateField(auto_now_add=True)

    def as_dict(self):
        return {
            "friend_name": self.friend_name,
            "npm": self.npm,
        }

lab_7/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt, ensure_csrf_cookie
from .models import Friend
from .api_csui_helper.csui_helper import CSUIhelper
from django.core import serializers
import os
import json

response = {}
csui_helper = CSUIhelper()

def index(request):
    mahasiswa_list = csui_helper.instance.get_mahasiswa_list()
    page = request.GET.get('page',1)
    paginator = Paginator(mahasiswa_list, 10)
    try:
        mahasiswa = paginator.page(page)
    except PageNotAnInteger:
        mahasiswa = paginator.page(1)
    except EmptyPage:
        mahasiswa = paginator.page(paginator.num_pages)
    friend_list = Friend.objects.all()
    html = 'lab_7/lab_7.html'
    response = {"mahasiswa_list": mahasiswa, "friend_list": friend_list}
    return render(request, html, response)

def friend_list(request):
    friend_list = Friend.objects.all()
    response['friend_list'] = friend_list
    html = 'lab_7/daftar-teman.html'
    return render(request, html, response)

def friend_list_json(request): # update
    friends = [obj.as_dict() for obj in Friend.objects.all()]
    return JsonResponse({"results": friends}, content_type='application/json')

@csrf_exempt
def add_friend(request):
    if request.method == 'POST':
        npm = request.POST['npm']
        name = request.POST['name']
        friend = Friend(friend_name=name, npm=npm)
        friend.save()
        return HttpResponse("berhasil")

@csrf_exempt
def delete_friend(request, npm):
    Friend.objects.filter(npm=npm).delete()
    return HttpResponse("berhasil")

@csrf_exempt
def validate_npm(request):
    npm = request.POST.get('npm', None)
    data = {
        'is_taken': Friend.objects.filter(npm=npm).exists()
    }
    return JsonResponse(data)

def model_to_dict(obj):
    data = serializers.serialize('json', [obj,])
    struct = json.loads(data)
    data = json.dumps(struct[0]["fields"])
    return data

lab_7/templates/lab_7/daftar-teman.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
    <section name="friend-list" id="friend-list">
        <div class="container">
            <div class="row" >
                <div class="col-md-8 col-lg-12">
                    <h2> Friend Fasilkom</h2>
                    <div id="friend-lists" class="list-group">

                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block javascript %}
    <script>
    var hapus = function(npm){
      $.ajax({
        method: "DELETE",
        url: "/lab-7/delete-friend/" + npm + "/",
        data: {npm:npm},
        success: function(data){
          $('#'+npm).remove()
        },
        error: function(error){
          alert('error')
        },
      });
    };

    var tes = function(data){
      for (i = 0; i < data.length; i++) {
        npm = data[i]['npm']
        html = '<p id="'+ npm +'" class="list-group-item clearfix">' +
            data[i]['friend_name']+ ' (' + data[i]['npm'] + ')' + '<a class="float-right"><span onClick="hapus(' + "&#39;" + npm + "&#39;" + ')" class="btn btn-dark float-right">Hapus sebagai teman</span></a></p>';
        $("#friend-lists").append(html);
      };
    };
        $( document ).ready(function () {
            $.ajax({
                method: "GET",
                url: "{% url 'lab-7:get-friend-list' %}", // update
                dataType: "json",
                success: function (result) {
                  console.log(result);
                  tes(result['results']);
                  },
                error: function(error){
                    alert(error.responseText)
                },
            });
        });
    </script>
{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="mahasiswa-list" id="mahasiswa-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> Mahasiswa Fasilkom</h2>
                <div class="list-group">
                    {% if mahasiswa_list %}
                        {% for mahasiswa in mahasiswa_list %}
                            <a class="list-group-item clearfix">
                                {{ mahasiswa.nama }} ({{ mahasiswa.npm }})
                                <span class="float-right">
                        <span class="btn btn-dark" onClick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}')">
                            Tambah sebagai teman
                        </span>
                    </span>
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada mahasiswa
                        </div>
                    {% endif %}
                </div>

                {% if mahasiswa_list.has_other_pages %}
                  <ul class="pagination">
                    {% if mahasiswa_list.has_previous %}
                      <li class="page-item"><a href="?page={{ mahasiswa_list.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                      <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}
                    {% for i in mahasiswa_list.paginator.page_range %}
                      {% if mahasiswa_list.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                      {% else %}
                        <li class="page-item"><a href="?page={{ i }}">{{ i }}</a></li>
                      {% endif %}
                    {% endfor %}
                    {% if mahasiswa_list.has_next %}
                      <li class="page-item"><a href="?page={{ mahasiswa_list.next_page_number }}">&raquo;</a></li>
                    {% else %}
                      <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                  </ul>
                {% endif %}

            </div>
            <div class="col-lg-4">
                <h2> Teman Saya </h2>
                <div class="list-group" id="friend-list">
                    {% if friend_list %}
                        {% for friend in friend_list %}
                            <a class="list-group-item clearfix">
                                {{ friend.friend_name }} ({{ friend.npm }})
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada teman
                        </div>
                    {% endif %}
                </div>
                <form id="add-friend" action="#">
                    {% csrf_token %}
                    <label for="field_npm">NPM</label>
                    <input id="field_npm" type="text" name="npm" class="form-control"/>
                    <label for="field_name">Name</label>
                    <input id="field_name" type="text" name="name" class="form-control"/>
                    <button type="submit" class="btn btn-dark" style="margin-top:10px">Tambah</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block javascript %}
<script>
    var addFriend = function(nama, npm) {
        $.ajax({
            method: "POST",
            url: "{% url "lab-7:add-friend" %}",
            data: { name: nama, npm: npm},
            success : function (response) {
                html = '<a class="list-group-item clearfix">' +
                    nama+ ' (' + npm + ')' +
                    '</a>';
                $("#friend-list").append(html)
            },
            error : function (error) {
                alert(error.responseText)
            }
        });
    };

    $("#add-friend").submit(function (event) {
       name = $("#field_name").val()
       npm = $("#field_npm").val()
       addFriend(name, npm);
       event.preventDefault();
       $('#add-friend')[0].reset();
    });

    $("#field_npm").change(function () {
        console.log( $(this).val() );
        npm = $(this).val();
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:validate-npm" %}',
            data: {
                'npm': npm
            },
            dataType: 'json',
            success: function (data) {
                console.log(data)
                if (data.is_taken) {
                    alert("Mahasiswa dengan npm seperti ini sudah ada");
                }
            }
        });
    });
</script>
{% endblock %}